// songs.js — Bruce Springsteen song catalog for Bossle
// audioFile: filename in the audio/ folder (no extension)

const SONGS = [
  { title: "Born to Run",                     album: "Born to Run",                                    year: 1975, audioFile: "born_to_run" },
  { title: "Thunder Road",                    album: "Born to Run",                                    year: 1975, audioFile: "thunder_road" },
  { title: "Jungleland",                      album: "Born to Run",                                    year: 1975, audioFile: "jungleland" },
  { title: "Tenth Avenue Freeze-Out",         album: "Born to Run",                                    year: 1975, audioFile: "tenth_avenue_freeze_out" },
  { title: "Born in the U.S.A.",              album: "Born in the U.S.A.",                             year: 1984, audioFile: "born_in_the_usa" },
  { title: "Dancing in the Dark",             album: "Born in the U.S.A.",                             year: 1984, audioFile: "dancing_in_the_dark" },
  { title: "Glory Days",                      album: "Born in the U.S.A.",                             year: 1984, audioFile: "glory_days" },
  { title: "Cover Me",                        album: "Born in the U.S.A.",                             year: 1984, audioFile: "cover_me" },
  { title: "I'm on Fire",                     album: "Born in the U.S.A.",                             year: 1984, audioFile: "im_on_fire" },
  { title: "Atlantic City",                   album: "Nebraska",                                       year: 1982, audioFile: "atlantic_city" },
  { title: "Nebraska",                        album: "Nebraska",                                       year: 1982, audioFile: "nebraska" },
  { title: "Highway Patrolman",               album: "Nebraska",                                       year: 1982, audioFile: "highway_patrolman" },
  { title: "Darkness on the Edge of Town",    album: "Darkness on the Edge of Town",                   year: 1978, audioFile: "darkness_on_the_edge_of_town" },
  { title: "The Promised Land",               album: "Darkness on the Edge of Town",                   year: 1978, audioFile: "the_promised_land" },
  { title: "Badlands",                        album: "Darkness on the Edge of Town",                   year: 1978, audioFile: "badlands" },
  { title: "Adam Raised a Cain",              album: "Darkness on the Edge of Town",                   year: 1978, audioFile: "adam_raised_a_cain" },
  { title: "The Ties That Bind",              album: "The River",                                      year: 1980, audioFile: "the_ties_that_bind" },
  { title: "Hungry Heart",                    album: "The River",                                      year: 1980, audioFile: "hungry_heart" },
  { title: "The River",                       album: "The River",                                      year: 1980, audioFile: "the_river" },
  { title: "Point Blank",                     album: "The River",                                      year: 1980, audioFile: "point_blank" },
  { title: "Tunnel of Love",                  album: "Tunnel of Love",                                 year: 1987, audioFile: "tunnel_of_love" },
  { title: "Brilliant Disguise",              album: "Tunnel of Love",                                 year: 1987, audioFile: "brilliant_disguise" },
  { title: "Human Touch",                     album: "Human Touch",                                    year: 1992, audioFile: "human_touch" },
  { title: "Streets of Philadelphia",         album: "Philadelphia OST",                               year: 1993, audioFile: "streets_of_philadelphia" },
  { title: "The Ghost of Tom Joad",           album: "The Ghost of Tom Joad",                          year: 1995, audioFile: "the_ghost_of_tom_joad" },
  { title: "The Rising",                      album: "The Rising",                                     year: 2002, audioFile: "the_rising" },
  { title: "Lonesome Day",                    album: "The Rising",                                     year: 2002, audioFile: "lonesome_day" },
  { title: "Radio Nowhere",                   album: "Magic",                                          year: 2007, audioFile: "radio_nowhere" },
  { title: "Girls in Their Summer Clothes",   album: "Magic",                                          year: 2007, audioFile: "girls_in_their_summer_clothes" },
  { title: "We Take Care of Our Own",         album: "Wrecking Ball",                                  year: 2012, audioFile: "we_take_care_of_our_own" },
  { title: "Death to My Hometown",            album: "Wrecking Ball",                                  year: 2012, audioFile: "death_to_my_hometown" },
  { title: "Wrecking Ball",                   album: "Wrecking Ball",                                  year: 2012, audioFile: "wrecking_ball" },
  { title: "High Hopes",                      album: "High Hopes",                                     year: 2014, audioFile: "high_hopes" },
  { title: "Rosalita (Come Out Tonight)",     album: "The Wild, the Innocent & the E Street Shuffle",  year: 1973, audioFile: "rosalita" },
  { title: "4th of July, Asbury Park (Sandy)", album: "The Wild, the Innocent & the E Street Shuffle", year: 1973, audioFile: "sandy" },
  { title: "Incident on 57th Street",         album: "The Wild, the Innocent & the E Street Shuffle",  year: 1973, audioFile: "incident_on_57th_street" },
  { title: "Spirit in the Night",             album: "Greetings from Asbury Park, N.J.",               year: 1973, audioFile: "spirit_in_the_night" },
  { title: "Blinded by the Light",            album: "Greetings from Asbury Park, N.J.",               year: 1973, audioFile: "blinded_by_the_light" },
  { title: "Prove It All Night",              album: "Darkness on the Edge of Town",                   year: 1978, audioFile: "prove_it_all_night" },
  { title: "Racing in the Street",            album: "Darkness on the Edge of Town",                   year: 1978, audioFile: "racing_in_the_street" },
  { title: "I'm Goin' Down",                  album: "Born in the U.S.A.",                             year: 1984, audioFile: "im_goin_down" },
  { title: "My Hometown",                     album: "Born in the U.S.A.",                             year: 1984, audioFile: "my_hometown" },
  { title: "No Surrender",                    album: "Born in the U.S.A.",                             year: 1984, audioFile: "no_surrender" },
  { title: "Secret Garden",                   album: "Greatest Hits",                                  year: 1995, audioFile: "secret_garden" },
  { title: "Waitin' on a Sunny Day",          album: "The Rising",                                     year: 2002, audioFile: "waitin_on_a_sunny_day" },
  { title: "Land of Hope and Dreams",         album: "Wrecking Ball",                                  year: 2012, audioFile: "land_of_hope_and_dreams" },
  { title: "Jack of All Trades",              album: "Wrecking Ball",                                  year: 2012, audioFile: "jack_of_all_trades" },
  { title: "Letter to You",                   album: "Letter to You",                                  year: 2020, audioFile: "letter_to_you" },
  { title: "Ghosts",                          album: "Letter to You",                                  year: 2020, audioFile: "ghosts" },
  { title: "Only the Strong Survive",         album: "Only the Strong Survive",                        year: 2022, audioFile: "only_the_strong_survive" },
];

// Sorted alphabetically for autocomplete
const SONGS_SORTED = [...SONGS].sort((a, b) => a.title.localeCompare(b.title));
